
[platformio]
src_dir = src
default_envs = esp32

[env]
platform = platformio/espressif32
board = esp32dev
framework = espidf
build_type = release
board_build.esp-idf.preserve_source_file_extension = yes
build_flags =
    -Os
    -DESP32

[env:esp32]
