[platformio]
src_dir = src
default_envs = empty, aether

[env]
platform = platformio/espressif32
board = esp-wrover-kit
framework = espidf
build_type = release
board_build.esp-idf.preserve_source_file_extension = yes
build_flags =
    -Os
    -DESP32
    -ffunction-sections
    -fdata-sections
    -I../include
    -I../src
    -I../third_party/libhydrogen

[env:empty]

[env:aether]
build_flags =
    ${env.build_flags}
    -DAETHER_SIZE_WITH_CLIENT=1

[env:p256-probe]
extends = env:aether
build_flags =
    ${env:aether.build_flags}
    -DAETHER_SIZE_WITH_P256

[env:p256]
extends = env:aether
build_flags =
    ${env:aether.build_flags}
    -DAETHER_SIZE_WITH_P256_BACKEND=1
    -I../platform/esp32

[env:p256-vectors]
extends = env:aether
build_flags =
    ${env:aether.build_flags}
    -DAETHER_P256_VECTOR_TEST=1

    -I../platform/esp32
    -DAETHER_ESP32_DISABLE_CBC=1
    -Wl,--wrap=esp_aes_crypt_cbc

[env:esp32-port]
extends = env:aether
build_flags =
    ${env:aether.build_flags}
    -DAETHER_SIZE_WITH_PUBLIC_API=1
    -DAETHER_SIZE_WITH_ESP32_PORT=1
    -DAETHER_SIZE_WITH_P256_BACKEND=1
    -DAETHER_PLATFORM_CONTEXT_BYTES=3200u

    -I../platform/esp32
    -DAETHER_ESP32_DISABLE_CBC=1
    -Wl,--wrap=esp_aes_crypt_cbc
